name: tooling-be.ownership-comment
# Controls when the workflow will run
on:
  pull_request:
    branches: [ "main" ]
    
env:
  CODEOWNER_SEARCH_COMMENT_PREFIX: 'Notifying code owners:'
  MY_GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  DOTNET_VERSION: '6.0.x'
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 
  
jobs:
  notify-comment:

    runs-on: ubuntu-latest
    steps:
  
      - name: API LIMIT BEFORE
        shell: pwsh
        run: |
          $response = & gh api rate_limit     	
          echo $response
          
      - name: git
        run: |
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git init
          git --version
          git config user.name 'mhascak'
          git config user.email 'martinhascak@gmail.com'
          
          git clone --filter=blob:none --sparse git@github.com:mhascak/GithubActionTests.git
          git sparse-checkout add tools
          
          git status

      - name: API LIMIT AFTER
        shell: pwsh
        run: |
          $response = & gh api rate_limit     	
          echo $response
