name: tooling-be.ownership-comment
# Controls when the workflow will run
on:
  pull_request:
    branches: [ "main" ]
    
env:
  MY_GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  DOTNET_VERSION: '6.0.x'
  
jobs:
  notify-comment:

    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Get PR Files
        id: PrCheck
        shell: pwsh
        run: |
          $response = & gh api repos/mhascak/GithubActionTests/pulls/${{ github.event.pull_request.number }}/files      	
          $usersObject = ConvertFrom-Json –InputObject $response
          $changedFiles = $usersObject | select -ExpandProperty filename
          echo $changedFiles
          echo "::set-output name=files::${changedFiles}")
          
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          
      - name: Install dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build --configuration Release --no-restore
        
      - name: Test
        run: dotnet test --no-restore --verbosity normal
        
      - name: Call owneship TOOL
        shell: pwsh
        run: echo ${{ steps.PrCheck.outputs.files }}
        continue-on-error: false

      - name: List files
        run: ls
#
#      - name: CodeOwnersParser
#        id: CodeOwnersParser
#        uses: Gamer025/CodeOwnersParser@v1
#        with:
#          #We don't specify the botname so we always get all owners returned, because we are replacing the existing comment
#          #If we were appending or always posting a new comment botname should be specified
#          prefix: 'Notifying code owners: '
#
#      - name: Check if already commented
#        uses: peter-evans/find-comment@v1
#        id: find-comment
#        with:
#          issue-number: ${{ github.event.number }}
#          comment-author: 'github-actions[bot]'
#          body-includes: 'Notifying code owners: '
#      
#      #If no existing comment exists create a new one if there were any owners found
#      - name: Create new comment
#        if: steps.find-comment.outputs.comment-id == '' && steps.CodeOwnersParser.outputs.owners != ''
#        uses: peter-evans/create-or-update-comment@v1
#        with:
#          issue-number: ${{ github.event.number }}
#          body: |
#            ${{ steps.CodeOwnersParser.outputs.owners-formatted }}
#      
#      #If existing comment was found replace it
#      - name: Update existing comment
#        if: steps.find-comment.outputs.comment-id != '' && steps.CodeOwnersParser.outputs.owners != ''
#        uses: peter-evans/create-or-update-comment@v1
#        with:
#          comment-id: ${{ steps.find-comment.outputs.comment-id }}
#          edit-mode: replace
#          body: |
#            ${{ steps.CodeOwnersParser.outputs.owners-formatted }}
