name: tooling-be.ownership-comment
# Controls when the workflow will run
on:
  pull_request:
    branches: [ "main" ]
    
env:
  CODEOWNER_SEARCH_COMMENT_PREFIX: 'Notifying code owners:'
  MY_GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  DOTNET_VERSION: '6.0.x'
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 
  
jobs:
  notify-comment:

    runs-on: ubuntu-latest
    steps:
  
      - name: API LIMIT BEFORE
        shell: pwsh
        run: |
          $response = & gh api rate_limit     	
          echo $response
    
      - name: Checkout files
        uses: Bhacaz/checkout-files@v2
        with:
         files: tools .github

      - name: Install dependencies
        run: dotnet restore
        working-directory: ./tools/TestConsoleApp
        
      - name: Build
        run: dotnet build --configuration Release --no-restore
        working-directory: ./tools/TestConsoleApp
        
      - name: Run owneship TOOL
        id: CodeOwnersParser
        shell: pwsh
        run: |
          $output = & ${{ github.workspace }}/tools/TestConsoleApp/TestConsoleApp/bin/Release/net6.0/TestConsoleApp > output.txt
          $reportData = (Get-Content ${{ github.workspace }}/output.txt) -join "%0A"
          echo "::set-output name=owners::${reportData}"
        continue-on-error: false
        

            
      - name: API LIMIT AFTER
        shell: pwsh
        run: |
          $response = & gh api rate_limit     	
          echo $response
